################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.c \
C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.c 

OBJS += \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.o \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.o 

C_DEPS += \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.d \
./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"
Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.o: C:/Users/dante/OneDrive/Documents/UCT/EEE4022F/ST\ Sensor/examples/Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.c Drivers/BSP/SensorTileBoxPro/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32U585xx -c -I../../Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc -I../../../../../../Drivers/STM32U5xx_HAL_Driver/Inc/Legacy -I../../../../../../Drivers/CMSIS/Device/ST/STM32U5xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/BSP/Components/Common -I../../../../../../Drivers/BSP/SensorTileBoxPro -I../../../../../../Drivers/BSP/Components/stc3115 -I../../../../../../Middlewares/ST/PnPLCompManager/Inc -I../../../../../../Middlewares/ST/STM32_BLE_Manager/Inc -I../../../../../../Middlewares/Third_Party/parson -I../../../../../../Middlewares/ST/BlueNRG-LP/hci/hci_tl_patterns/Basic -I../../../../../../Middlewares/ST/BlueNRG-LP/includes -I../../../../../../Middlewares/ST/BlueNRG-LP/utils -I../../../../../../Drivers/BSP/Components/lis2mdl -I../../../../../../Drivers/BSP/Components/lps22df -I../../../../../../Drivers/BSP/Components/lis2du12 -I../../../../../../Drivers/BSP/Components/stts22h -I../../../../../../Drivers/BSP/Components/lsm6dsv16x -I../../../../../../Drivers/BSP/Components/st25dvxxkc -I../../../../../../Drivers/BSP/Components/ST25DV -O0 -ffunction-sections -fdata-sections -Wall -Wno-format -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=softfp -mthumb -o "$@"

clean: clean-Drivers-2f-BSP-2f-SensorTileBoxPro

clean-Drivers-2f-BSP-2f-SensorTileBoxPro:
	-$(RM) ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_audio.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_env_sensors_ex.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_gg.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_motion_sensors_ex.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_nfctag_ex.su ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.cyclo ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.d ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.o ./Drivers/BSP/SensorTileBoxPro/SensorTileBoxPro_sd.su

.PHONY: clean-Drivers-2f-BSP-2f-SensorTileBoxPro

